### ISSUE TITLE
Tracking Ticket - DUNS Number for Apple Code Sign

### ISSUE THREAD

**Issue by Nicky-2000** [GadzeFinance/etherfi-desktop#66]

**Comment by brettgrigsby** [comment]
I have the DUNS number and have submitted for approval in the Apple developer program

**Comment by brettgrigsby** [comment]
Received an email asking for more info:

• Applicant’s government-issued photo ID
• Applicant’s employment verification letter
• Applicant’s employee badge or business card
• Business registration documents for Gadze Finance US, LLC
